# active spring boot profile
spring:
  profiles:
    active: dev

---
# common spring boot configuration
spring:

# mvc
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# http
  http:
    encoding:
      charset: UTF-8
      enabled: true
      forced: true
      forced-request: true
      forced-response: true

# message resource(Internationalization)# messages
  messages:
    always-message-format: true
    basename: messages/messages_ko
    encoding: UTF-8

# multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

# aop (@EnableAspectJAutoProxy)
  aop:
    auto: true
    proxy-target-class: true

---
# dev profile - spring boot configuration
spring:
  profiles: dev

# datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookmall_local
    username: bookmall_local
    password: bookmall_local
    initialSize: 10
    maxActive: 100  

  # devtools enabled 
  devtools:
    livereload:
      enabled: true

---
# production profile - spring boot configuration
spring:
  profiles: production

# datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.80.101:3307/webdb?characterEncoding=utf8
    username: webdb
    password: webdb
    initialSize: 10
    maxActive: 100

---
# server
server:
  port: 8080
  servlet:
    context-path: /mysite06

---
# mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml

# logging
logging:
  cofig: classpath:logback.xml

